name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    name: test minishell
    steps:
    - uses: actions/checkout@v3
    - name: install readline
      run: sudo apt-get install lib32readline8 lib32readline-dev
    - uses: actions/cache@v1.2.1
      with:
        packages: lib32readline8 lib32readline-dev
        path: /home/runner/.local/bin
    - name: make
      working-directory: merged_code
      run: make e
    - name: test
      run: this is a test
