name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    name: test minishell
    steps:
    - uses: actions/checkout@v3
    - name: update apt-get
      run: sudo apt-get update
    - name: install readline8
      run: sudo apt-get install lib32readline8
    - name: install readline-dev
      run: sudo apt-get install lib32readline-dev
      
    - uses: actions/cache@v1.2.1
      with:
        path: /home/runner/.local/bin
        key: test
    - name: make
      working-directory: full_merge
      run: make testing
    - name: start minishell
      working-directory: full_merge
      run: ./a.out "ls"
    - name: test
      run: ls
    - name: test
      run: blah
