name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    name: test minishell
    steps:
    - uses: actions/checkout@v3
    - name: update apt-get
      run: sudo apt-get update
    - name: install readline8
      run: sudo apt-get install lib32readline8
    - name: install readline-dev
      run: sudo apt-get install lib32readline-dev
    - name: check for readline
      run: find /usr | grep readline | grep 32git
      
    - uses: actions/cache@v1.2.1
      with:
        path: /home/runner/.local/bin
        key: test
    - name: make
      working-directory: merged_code
      run: make e
    - name: test
      run: this is a tes
